global using Ordering.Domain.Enums;
global using System.Reflection;
global using Microsoft.EntityFrameworkCore;
global using Ordering.Domain.Models;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Ordering.Domain.Primitives;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.DependencyInjection;
global using Ordering.Domain.ValueObject;