version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres
  
  distributedcache:
    image: redis
  
  orderdb:
    image: mcr.microsoft.com/azure-sql-edge
  
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering.Api/Dockerfile
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
